//! RFC 7807 / RFC 9457 `application/problem+json` error responses.
//!
//! Provides a typed [`Problem`] struct, a [`Responder`] implementation that
//! emits `application/problem+json`, and a helper that builds a default
//! problem response from a status code. Hook the helper into
//! [`Router::error_handler`](crate::router::Router::error_handler) /
//! [`Router::client_error_handler`](crate::router::Router::client_error_handler)
//! to upgrade plain text 4xx/5xx responses into structured problem documents.

use std::collections::BTreeMap;

use http::StatusCode;
use http::header::HeaderValue;
use serde::Deserialize;
use serde::Serialize;

use crate::body::TakoBody;
use crate::responder::Responder;
use crate::types::Response;

/// Media type for RFC 7807 problem details.
pub const PROBLEM_JSON: &str = "application/problem+json";

/// RFC 7807 / RFC 9457 problem details document.
///
/// All fields except `status` are optional. `extensions` carries any extra
/// implementation-specific members and is flattened into the JSON output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Problem {
  /// URI reference identifying the problem type. Defaults to `"about:blank"`.
  #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
  pub r#type: Option<String>,
  /// Short, human-readable summary of the problem.
  #[serde(skip_serializing_if = "Option::is_none")]
  pub title: Option<String>,
  /// HTTP status code generated by the origin server.
  pub status: u16,
  /// Human-readable explanation specific to this occurrence of the problem.
  #[serde(skip_serializing_if = "Option::is_none")]
  pub detail: Option<String>,
  /// URI reference identifying the specific occurrence.
  #[serde(skip_serializing_if = "Option::is_none")]
  pub instance: Option<String>,
  /// Extension members merged into the top-level object.
  #[serde(flatten)]
  pub extensions: BTreeMap<String, serde_json::Value>,
}

impl Problem {
  /// Builds a problem document from a status code, defaulting `title` to the
  /// canonical reason phrase.
  pub fn from_status(status: StatusCode) -> Self {
    Self {
      r#type: None,
      title: status.canonical_reason().map(str::to_string),
      status: status.as_u16(),
      detail: None,
      instance: None,
      extensions: BTreeMap::new(),
    }
  }

  /// Sets the `detail` field.
  pub fn with_detail(mut self, detail: impl Into<String>) -> Self {
    self.detail = Some(detail.into());
    self
  }

  /// Sets the `type` URI.
  pub fn with_type(mut self, type_uri: impl Into<String>) -> Self {
    self.r#type = Some(type_uri.into());
    self
  }

  /// Sets the `instance` URI.
  pub fn with_instance(mut self, instance: impl Into<String>) -> Self {
    self.instance = Some(instance.into());
    self
  }

  /// Adds an extension member.
  pub fn with_extension(
    mut self,
    key: impl Into<String>,
    value: impl Into<serde_json::Value>,
  ) -> Self {
    self.extensions.insert(key.into(), value.into());
    self
  }
}

impl Responder for Problem {
  fn into_response(self) -> Response {
    let status = StatusCode::from_u16(self.status).unwrap_or(StatusCode::INTERNAL_SERVER_ERROR);
    let body = serde_json::to_vec(&self).unwrap_or_else(|_| b"{}".to_vec());
    let mut res = Response::new(TakoBody::from(body));
    *res.status_mut() = status;
    res.headers_mut().insert(
      http::header::CONTENT_TYPE,
      HeaderValue::from_static(PROBLEM_JSON),
    );
    res
  }
}

/// Default problem-formatter to be installed into
/// [`Router::error_handler`](crate::router::Router::error_handler) and/or
/// [`Router::client_error_handler`](crate::router::Router::client_error_handler).
///
/// Behavior: if the incoming response already carries a JSON or `problem+json`
/// `Content-Type` header it is returned unchanged (handlers that produce their
/// own structured error stay authoritative). Otherwise the body is replaced
/// with a problem document built from the status code and any inline reason.
pub fn default_problem_responder(response: Response) -> Response {
  let status = response.status();

  if let Some(ct) = response.headers().get(http::header::CONTENT_TYPE) {
    if let Ok(s) = ct.to_str() {
      let s_lower = s.to_ascii_lowercase();
      if s_lower.contains("json") {
        return response;
      }
    }
  }

  let problem = Problem::from_status(status);
  problem.into_response()
}
