[package]
name = "webtransport-example"
version = "0.1.0"
edition = "2024"

[dependencies]
rcgen = { workspace = true }
sha2 = { workspace = true }
tako-rs = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }


[workspace]

[workspace.dependencies]
rcgen = "0.14"
sha2 = "0.10"
tako-rs = { path = "../../tako-rs", features = ["webtransport"] }
time = "0.3"
tokio = { version = "1.45.1", features = ["full"] }
