[package]
name = "multipart"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
http = "1.3.1"
serde = "1.0.219"
tako-rs = { path = "../..", features = ["multipart"] }
tokio = { version = "1.45.1", features = ["full"] }
