[package]
name = "streams"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bytes = "1.10.1"
futures-util = "0.3.31"
http = "1.3.1"
hyper = "1.6.0"
tako-rs = { path = "../.." }
tokio = { version = "1.45.1", features = ["full"] }
