[package]
name = "websockets"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
tako-rs = { path = "../.." }
tokio = { version = "1.45.1", features = ["full"] }
tokio-stream = "0.1.17"
tokio-tungstenite = "0.27.0"
