[package]
name = "file-stream"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
tako-rs = { path = "../..", features = ["file-stream"] }
tokio = { version = "1.45.1", features = ["full"] }
tokio-util = "0.7.15"
