//! Server-streaming, client-streaming, and bidirectional gRPC on Tako.
//!
//! Run the server, then call it with grpcurl from this directory:
//!
//! ```text
//! grpcurl -plaintext -import-path proto -proto numbers.proto \
//!   -d '{"value": 3}' 127.0.0.1:50051 numbers.Numbers/Count
//! grpcurl -plaintext -import-path proto -proto numbers.proto \
//!   -d '{"value": 1} {"value": 2} {"value": 3}' 127.0.0.1:50051 numbers.Numbers/Sum
//! grpcurl -plaintext -import-path proto -proto numbers.proto \
//!   -d '{"value": 1} {"value": 2} {"value": 3}' 127.0.0.1:50051 numbers.Numbers/RunningTotal
//! ```

use std::time::Duration;

use futures_util::StreamExt;
use prost::Message;
use tako::Method;
use tako::grpc::GrpcBidi;
use tako::grpc::GrpcClientStream;
use tako::grpc::GrpcDeadline;
use tako::grpc::GrpcRequest;
use tako::grpc::GrpcResponse;
use tako::grpc::GrpcServerStream;
use tako::grpc::GrpcStatus;
use tako::grpc::GrpcStatusCode;
use tako::responder::Responder;
use tako::router::Router;
use tako::types::BoxError;

/// Generated by `prost-build` from `proto/numbers.proto` in a real project.
#[derive(Clone, PartialEq, Message)]
pub struct Number {
  #[prost(int64, tag = "1")]
  pub value: i64,
}

/// Server streaming: one request, a stream of replies.
async fn count(
  deadline: Option<GrpcDeadline>,
  req: GrpcRequest<Number>,
) -> Result<impl Responder, GrpcStatus> {
  let last = req.message.value;
  if !(1..=100).contains(&last) {
    return Err(GrpcStatus::error(
      GrpcStatusCode::InvalidArgument,
      "value must be between 1 and 100",
    ));
  }
  let numbers = futures_util::stream::unfold(1, move |value| async move {
    if value > last {
      return None;
    }
    tokio::time::sleep(Duration::from_millis(200)).await;
    Some((Ok(Number { value }), value + 1))
  });
  // Ends the call with DEADLINE_EXCEEDED if the client's `grpc-timeout` passes.
  Ok(GrpcServerStream::new(numbers).with_deadline(deadline))
}

/// Client streaming: a stream of requests, one reply.
async fn sum(mut numbers: GrpcClientStream<Number>) -> Result<GrpcResponse<Number>, GrpcStatus> {
  let mut value = 0;
  while let Some(number) = numbers.next().await {
    value += number?.value;
  }
  Ok(GrpcResponse::ok(Number { value }))
}

/// Bidirectional streaming: each reply is sent as soon as its request arrives.
async fn running_total(bidi: GrpcBidi<Number, Number>) -> impl Responder {
  bidi.respond(|numbers| {
    numbers.scan(0, |total, number| {
      let reply = number
        .map(|number| {
          *total += number.value;
          Number { value: *total }
        })
        .map_err(GrpcStatus::from);
      futures_util::future::ready(Some(reply))
    })
  })
}

#[tokio::main]
async fn main() -> Result<(), BoxError> {
  let mut router = Router::new();
  router.route(Method::POST, "/numbers.Numbers/Count", count);
  router.route(Method::POST, "/numbers.Numbers/Sum", sum);
  router.route(Method::POST, "/numbers.Numbers/RunningTotal", running_total);

  let listener = tokio::net::TcpListener::bind("127.0.0.1:50051").await?;
  println!("gRPC (h2c) on http://127.0.0.1:50051");

  tako::Server::builder()
    .build()
    .try_spawn_h2c(listener, router)?
    .result()
    .await?;
  Ok(())
}
